package com.inventnow.projectx.security;

public enum RoleEnum {

    ADMIN,
    CUSTOMER_READ,
    CUSTOMER_UPDATE,
    CUSTOMER_DELETE,
    MERCHANT_SUPERVISOR_VIEW,
    MERCHANT_SUPERVISOR_UPDATE,
    MERCHANT_SUPERVISOR_DELETE,
    MERCHANT_CASHIER_VIEW
}
